GET http://localhost:4000/api/v1/member/landing-page

###
GET http://localhost:4000/api/v1/member/detail-page/5e96cbe292b97300fc902222

###
POST http://localhost:4000/api/v1/member/landing-page
Content-Type: application/json

{
    "firstName": "Orang 2 expressJs",
    "hobi": "Ngoding",
    "dob": "2021-12-29"
}

###
PUT http://localhost:4000/api/v1/member/landing-page/45
Content-Type: application/json

{
    "firstName": "Orang 1 expressJs",
    "hobi": "Traveling",
    "dob": "2021-12-29"
}

###
DELETE http://localhost:4000/api/v1/member/landing-page/46